In [66]:
import numpy as np

In [67]:
def matrix(n):
    result = np.zeros(shape=(n,n))
    for i in range(n):
        for j in range(n):
            result[i,j] = (i+1)**((j+1)/3)
    return result

тестовая проверочка на правильность генерации

In [68]:
matrix(5)

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.25992105,  1.58740105,  2.        ,  2.5198421 ,  3.1748021 ],
       [ 1.44224957,  2.08008382,  3.        ,  4.32674871,  6.24025147],
       [ 1.58740105,  2.5198421 ,  4.        ,  6.34960421, 10.0793684 ],
       [ 1.70997595,  2.92401774,  5.        ,  8.54987973, 14.62008869]])

In [69]:
def Eig(X):
    V = eig(X)[1]
    sigma = np.diag(eig(X)[0]**(0.5))
    return V @ sigma @ inv(V)

тестовая проверочка на взятие корня

In [70]:
Eig(matrix(5))

array([[0.7511801 , 0.49768388, 0.29385344, 0.14847792, 0.06249025],
       [0.53950606, 0.68491631, 0.67998191, 0.55222374, 0.35994597],
       [0.38938515, 0.63006621, 0.88146629, 1.02964961, 0.96748513],
       [0.27649709, 0.51285867, 0.89423841, 1.42036805, 1.92580864],
       [0.18801494, 0.38378227, 0.78493109, 1.60303577, 3.25939403]])

In [71]:
def Newt(X,eps):
    x1 = np.identity(X.shape[0])
    x2 = 0.5*(x1+inv(x1)@X)
    while norm(x2-x1)>eps:
        x1 = x2
        x2 = 0.5*(x1+inv(x1)@X)
    return x2

тестовая проверочка на взятие корня 2 способом

In [72]:
Newt(matrix(5),0.001)

array([[0.75118007, 0.49768168, 0.29385549, 0.14847412, 0.06248855],
       [0.53950616, 0.68492287, 0.67997578, 0.55223508, 0.35995103],
       [0.38938505, 0.63005896, 0.88147306, 1.02963711, 0.96747957],
       [0.27649713, 0.51286217, 0.89423513, 1.42037409, 1.92581132],
       [0.18801493, 0.38378165, 0.78493168, 1.60303469, 3.25939355]])

In [74]:
Cond = []

for i in range(1,6):
    M = matrix(i)
    BE = Eig(M)
    BN = Newt(M,0.001)
    Cond.append([i,cond(M),cond(BE),cond(BN),norm(BN@BN-M)])

print(tabulate(Cond,headers=['n','cnd1','cnd2','cnd3','norm((M - B^2))'],
               tablefmt='github',numalign="right"))

|   n |    cnd1 |    cnd2 |    cnd3 |   norm((M - B^2)) |
|-----|---------|---------|---------|-------------------|
|   1 |       1 |       1 |       1 |                 0 |
|   2 | 18.5954 | 4.32162 | 4.32162 |       1.21536e-11 |
|   3 | 323.477 | 18.0102 | 18.0102 |        5.7769e-09 |
|   4 | 6092.37 | 78.6235 | 78.6206 |       1.36149e-07 |
|   5 |  126576 | 363.439 | 362.953 |       7.15601e-05 |
